name: linter

on:
  push:
    branches:
      - development
      - release
  pull_request:
    branches:
      - development
      - release

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install

      - name: Format Frontend
        run: npm run format

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix code style
          commit_options: '--no-verify'
